apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-app
  labels:
    app: flask-todo-app
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: flask-todo-app
  template:
    metadata:
      labels:
        app: flask-todo-app
    spec:
      containers:
        - name: flask-todo-app
          image: amaa00/flask-todo-app:1.0
          port:
            - containerPort: 8000
